#wx config
#Tue May 19 05:36:54 JST 2026
tempFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/textFileFolder
returnCode=0
txtFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/tempFileFolder
endfileFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/endFileFolder
