#wx config
#Sun Sep 27 21:03:50 JST 2026
tempFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/tempFileFolder
returnCode=0
txtFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/textFileFolder
endfileFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/Test/endFileFolder
