#wx config
#Wed May 06 04:07:17 JST 2026
tempFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/tempFileFolder
returnCode=3221
txtFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/textFileFolder
endfileFolderPath=C\:/Users/Device2/workspace/WatchAndTransform/endFileFolder
